name: fourfury
services:
    backend:
        build: ./backend/
        container_name: fourfury-backend
        command: "poetry run uvicorn src.fourfury.run:app --reload --host 0.0.0.0 --port 8000"
        ports:
            - 8001:8000
        depends_on:
            - db
            - redis
        env_file:
            - "./backend/.env.docker"
    db:
        image: mongo
        container_name: fourfury-mongodb
        volumes:
            - "mongodb_data:/data/db"
        ports:
            - "27018:27017"

    redis:
        image: redis:latest
        container_name: fourfury-redis
        ports:
            - "6379:6379"
        volumes:
            - "redis_data:/data"

volumes:
    mongodb_data:
    redis_data:
