name: fourfury
services:
    nginx:
        image: nginx:latest
        container_name: fourfury-nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - backend
        networks:
            - app-network

    frontend:
        build: ./frontend/
        container_name: fourfury-frontend
        depends_on:
            - backend
        env_file:
            - "./frontend/.env.docker"
        networks:
            - app-network

    backend:
        build: ./backend/
        container_name: fourfury-backend
        command: "poetry run uvicorn src.fourfury.run:app --reload --host 0.0.0.0 --port 8000"
        depends_on:
            - db
            - redis
        env_file:
            - "./backend/.env.docker"
        networks:
            - app-network

    db:
        image: mongo
        container_name: fourfury-mongodb
        volumes:
            - "mongodb_data:/data/db"
        networks:
            - app-network

    redis:
        image: redis:latest
        container_name: fourfury-redis
        command: redis-server --notify-keyspace-events Ex
        volumes:
            - "redis_data:/data"
        networks:
            - app-network

volumes:
    mongodb_data:
    redis_data:

networks:
    app-network:
        driver: bridge
